name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew checkVersion build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - run: ./gradlew processMDTemplates
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Update readme
#          commit_author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
