name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
#      - uses: FabricMC/fabric-action-scripts@v2
#        id: changelog
#        with:
#          context: changelog
#          workflow_id: release.yml
      - run: ./gradlew build publish --stacktrace --warning-mode=fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - run: ./gradlew processMDTemplates
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Update readme
#          commit_author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
